def listaProducto():
    print("lista d productos")
    print("1. coca cola")
    print("2. cheetos")
    print("3. maruchan")
    print("4. palomeras")
    print("5. gomitas")
    print("6. fruta")
    print("7. helado")
    print("8. papel higienico")
    print("9. verdura")
    print("10 gansito")